### PR TITLE
Added about us page

### PR DESCRIPTION
**Pull request by mlong505**

### CODE REVIEW

**Comment by chencbs** [comment]
Add more text to page!

**Comment by chencbs** [comment]
:+1:

**Comment by chencbs** [comment]
:+1:

**Comment by chencbs** [comment]
:+1:  :-1:  :+1:  :-1:

**Comment by idimkova** [comment]
cooolio

**Comment by chencbs** [comment]
:cow: :cow2: :cat: :panda_face: :bear:

**Comment by chencbs** [comment]
:hankey: :toilet:

**Pull request merged**
